[package]
name = "plonk_circuits"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
mina-curves = { path = "../../curves" }
ocaml = { version = "0.22.0", optional = true }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
array-init = { version = "1.0.0" }
rayon = { version = "1" }
blake2 = "0.7"

num-derive = "0.3"
num-traits = "0.2"

[features]

ocaml_types = [ "ocaml", "oracle/ocaml_types" ]
