[package]
name = "circuits_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { git = "https://github.com/o1-labs/zexe/", rev = "8b67d7", features = [ "parallel" ] }
ff-fft = { git = "https://github.com/o1-labs/zexe/", rev = "8b67d7" }
commitment_dlog = { path = "../commitment" }
oracle = { path = "../../oracle" }
evaluation_domains = { path = "../../evaluation_domains" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
sprs = "0.7.1"
