[package]
name = "kimchi_optimism"
version = "0.1.0"
description = "MIPS demo"
repository = "https://github.com/o1-labs/proof-systems"
homepage = "https://o1-labs.github.io/proof-systems/"
documentation = "https://o1-labs.github.io/proof-systems/rustdoc/"
readme = "README.md"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
ark-bn254 = { version = "0.3.0" }
kimchi = { path = "../kimchi", version = "0.1.0", features = [ "bn254" ] }
poly-commitment = { path = "../poly-commitment", version = "0.1.0" }
groupmap = { path = "../groupmap", version = "0.1.0" }
mina-curves = { path = "../curves", version = "0.1.0" }
mina-poseidon = { path = "../poseidon", version = "0.1.0" }
elf = "0.7.2"
rmp-serde = "1.1.1"
serde_json = "1.0.91"
serde = "1.0.130"
serde_with = "1.10.0"
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
ark-ff = { version = "0.3.0", features = [ "parallel" ] }
clap = "4.4.6"
hex = "0.4.3"
regex = "1.10.2"
libflate = "2"
base64 = "0.21.5"
strum = "0.24.0"
strum_macros = "0.24.0"
log = "0.4.20"
env_logger = "0.10.0"
