[package]
name = "plonk_5_wires_protocol_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
mina-curves = { path = "../../curves" }
commitment_dlog = { path = "../commitment" }
plonk_5_wires_circuits = { path = "../../circuits/plonk-5-wires" }
oracle = { path = "../../oracle" }
colored = "2.0.0"
rand = "0.8.0"
sprs = "0.9.2"
rayon = "1.5.0"
array-init = "1.0.0"

# ocaml-specific dependencies
ocaml = { version = "0.18.1", optional = true }
itertools = { version = "0.10.1", optional = true }

[features]

ocaml_types = [ "ocaml", "itertools", "plonk_5_wires_circuits/ocaml_types", "commitment_dlog/ocaml_types" ]
