[package]
name = "mina-curves"
version = "0.1.0"
edition = "2018"

[dependencies]
ark-ec = { version = "0.3.0", features = ["parallel"] }
ark-ff = { version = "0.3.0", features = ["parallel", "asm"] }

[dev-dependencies]
rand = { version = "0.8.0", default-features = false }
rand_xorshift = "0.2"
ark-algebra-test-templates = "0.3.0"
ark-std = "0.3.0"
