[package]
name = "groupmap"
version = "0.1.0"
description = "A group map implementation"
repository = "https://github.com/o1-labs/proof-systems"
homepage = "https://o1-labs.github.io/proof-systems/"
documentation = "https://o1-labs.github.io/proof-systems/rustdoc/"
readme = "../README.md"
authors = ["Rebekah Mercer <github@rbkhmrcr.com>", "Izaak Meckler <izaak@o1labs.org>"]
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = { version = "0.4.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.4.0", features = [ "parallel" ] }
rand = "0.8.4"

[dev-dependencies]
mina-curves = { path = "../curves", version = "0.1.0" }
