[package]
name = "cairo-circuits"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
ark-serialize = "0.3.0"
array-init = { version = "1.0.0" }
rayon = { version = "1" }
blake2 = "0.9.1"
rand = "0.8.0"
rand_core = { version = "0.5" }
num-derive = "0.3"
num-traits = "0.2"
itertools = "0.10.1"
serde = "1.0.130"
serde_with = "1.10.0"

mina-curves = { path = "../../curves" }
o1-utils = { path = "../../utils" }
oracle = { path = "../../oracle" }

ocaml = { version = "0.22.2", optional = true }
ocaml-gen = { path = "../../ocaml/ocaml-gen", optional = true }

[dev-dependencies]
rmp-serde = "0.15.5"
proptest = "1.0.0"
proptest-derive = "0.3.0"

[features]
default = []
ocaml_types = [ "ocaml", "ocaml-gen", "oracle/ocaml_types" ]
