[package]
name = "export_test_vectors"
version = "0.1.0"
description = "Runs the tests vectors for the mina-poseidon crate"
repository = "https://github.com/o1-labs/proof-systems"
homepage = "https://o1-labs.github.io/proof-systems/"
documentation = "https://o1-labs.github.io/proof-systems/rustdoc/"
readme = "../README.md"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ark-ff = { version = "0.4.0", features = [ "parallel", "asm" ] }
num-bigint = { version = "0.4.0" }
serde_json = { version = "1.0" }
hex = { version = "0.4" }
ark-serialize = { version = "0.4.0" }
rand = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.10.0"

mina-curves = { path = "../../curves", version = "0.1.0" }
mina-poseidon = { path = "../../poseidon", version = "0.1.0" }

