[package]
name = "pairing"
version = "0.1.0"
edition = "2018"

[dependencies]
algebra = { path = "../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
ff-fft = { path = "../zexe/ff-fft" }
commitment_pairing = { path = "commitment" }
marlin_circuits = { path = "../circuits/marlin" }
marlin_protocol_pairing = { path = "marlin" }
oracle = { path = "../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
sprs = "0.7.1"
wasm-bindgen = "0.2.69"

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
