[package]
name = "pairing"
version = "0.1.0"
edition = "2018"

[dependencies]
algebra = { path = "../../zexe/algebra/", features = [ "asm", "parallel", "bn_382", "tweedle" ] }
ff-fft = { path = "../../zexe/ff-fft" }
commitment_pairing = { path = "commitment" }
marlin_circuits = { path = "../circuits/marlin" }
marlin_protocol_pairing = { path = "marlin" }
plonk_circuits = { path = "../circuits/plonk" }
plonk_protocol_pairing = { path = "plonk" }
oracle = { path = "../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
sprs = "0.7.1"
