[package]
name = "plonk_protocol_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
mina-curves = { path = "../../curves" }
commitment_dlog = { path = "../commitment" }
plonk_circuits = { path = "../../circuits/plonk" }
ocaml = { version = "0.22.0", optional = true }
oracle = { path = "../../oracle" }
rand_core = "0.6.0"
colored = "1.9.3"
rand = "0.8.0"
sprs = "0.7.1"
rayon = "1.3.0"
array-init = "1.0.0"

[features]

ocaml_types = [ "ocaml", "plonk_circuits/ocaml_types", "commitment_dlog/ocaml_types" ]
