[package]
name = "plonk_protocol_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
rand_core = "0.6.0"
colored = "1.9.3"
rand = "0.8.0"
sprs = "0.7.1"
rayon = "1.3.0"
array-init = "1.0.0"

commitment_dlog = { path = "../commitment" }
mina-curves = { path = "../../curves" }
o1-utils = { path = "../../utils" }
oracle = { path = "../../oracle" }
plonk_circuits = { path = "../../circuits/plonk" }

ocaml = { version = "0.22.2", optional = true }
ocaml-gen = { path = "../../ocaml/ocaml-gen", optional = true }

[features]

ocaml_types = [ "ocaml", "ocaml-gen", "plonk_circuits/ocaml_types", "commitment_dlog/ocaml_types" ]
