[package]
name = "plonk_protocol_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../../zexe/algebra/", features = [ "asm", "parallel", "bn_382", "tweedle" ] }
ff-fft = { path = "../../../zexe/ff-fft" }
commitment_dlog = { path = "../commitment" }
plonk_circuits = { path = "../../circuits/plonk" }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.3"
rand = "0.7.3"
sprs = "0.7.1"
rayon = "1.3.0"
array-init = "0.1.1"
