[package]
name = "arkworks"
edition.workspace = true
version.workspace = true

[features]
default = ["wasm"]
wasm = []
std = []

[dependencies]
# arkworks
ark-ec.workspace = true
ark-ff.workspace = true
ark-poly.workspace = true
ark-serialize.workspace = true

# proof-systems
mina-curves.workspace = true
num-bigint.workspace = true
rand.workspace = true
wasm-bindgen.workspace = true
wasm-types.workspace = true
