[package]
name = "mina-signer"
version = "0.1.0"
description = "The mina signer"
repository = "https://github.com/o1-labs/proof-systems"
homepage = "https://o1-labs.github.io/proof-systems/"
documentation = "https://o1-labs.github.io/proof-systems/rustdoc/"
readme = "README.md"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ec.workspace = true
ark-ff.workspace = true
bitvec.workspace = true
blake2.workspace = true
bs58.workspace = true
hex.workspace = true
mina-curves.workspace = true
mina-hasher.workspace = true
o1-utils.workspace = true
rand.workspace = true
sha2.workspace = true
thiserror.workspace = true