[metadata]
name = "Polynomial Commitment"
description = "This specification describes the Kimchi polynomial commitment."
version = "0.1.0"
authors = ["TODO: ENTER ALL THE NAMES"]

[config]
template = "template.md"

[sections]
verifier = "../../poly-commitment/src/lib.rs"
