[package]
name = "plonk_protocol_pairing"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
ark-poly = "0.2.0"
commitment_pairing = { path = "../commitment" }
plonk_circuits = { path = "../../circuits/plonk" }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
sprs = "0.7.1"
array-init = "0.1.1"
