[package]
name = "plonk_protocol_pairing"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { git = "https://github.com/o1-labs/zexe/", features = [ "parallel" ] }
ff-fft = { git = "https://github.com/o1-labs/zexe/" }
commitment_pairing = { path = "../commitment" }
plonk_circuits = { path = "../../circuits/plonk" }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
sprs = "0.7.1"
array-init = "0.1.1"
