[package]
name = "export_test_vectors"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
num-bigint = { version = "0.4.0" }
serde_json = { version = "1.0" }
hex = { version = "0.4" }
ark-serialize = { version = "0.3.0" }
rand = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.10.0"

mina-curves = { path = "../../curves" }
oracle = { path = "../../oracle" }

