[metadata]
name = "Kimchi"
description = "This specification describes the Kimchi proof system."
version = "0.1.0"
authors = ["Izaak Meckler", "Vanishree Rao", "Matthew Ryan", "Joseph Spadavecchia", "David Wong", "Vitaly Zelov"]

[config]
template = "template.md"

[sections]
# permutation
permutation = "../../../kimchi/src/circuits/polynomials/permutation.rs"

# gates
chacha = "../../../kimchi/src/circuits/polynomials/chacha.rs"
complete_add = "../../../kimchi/src/circuits/polynomials/complete_add.rs"
endomul_scalar = "../../../kimchi/src/circuits/polynomials/endomul_scalar.rs"
endosclmul = "../../../kimchi/src/circuits/polynomials/endosclmul.rs"
generic = "../../../kimchi/src/circuits/polynomials/generic.rs"
poseidon = "../../../kimchi/src/circuits/polynomials/poseidon.rs"
varbasemul = "../../../kimchi/src/circuits/polynomials/varbasemul.rs"

# lookup
tables = "../../../kimchi/src/circuits/lookup/tables/mod.rs"
xor = "../../../kimchi/src/circuits/lookup/tables/xor.rs"
lookup = "../../../kimchi/src/circuits/lookup/constraints.rs"
lookup_index = "../../../kimchi/src/circuits/lookup/index.rs"

# setup
constraint_system = "../../../kimchi/src/circuits/constraints.rs"
prover_index = "../../../kimchi/src/prover_index.rs"
verifier_index = "../../../kimchi/src/verifier_index.rs"

# proof
proof = "../../../kimchi/src/proof.rs"
prover = "../../../kimchi/src/prover.rs"
verifier = "../../../kimchi/src/verifier.rs"
