[book]
authors = ["Izaak Meckler", "Vanishree Rao", "Matthew Ryan", "Joseph Spadavecchia", "David Wong", "Vitaly Zelov"]
language = "en"
multilingual = false
src = "src"
title = "Mina book"

[output.html]
site-url = "/proof-systems/"
curly-quotes = true
git-repository-url = "https://www.github.com/o1-labs/proof-systems"
additional-css = ["./assets/css/mdbook-admonish.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

# for LaTeX
[preprocessor.katex]

# for callouts
[preprocessor.admonish]
command = "mdbook-admonish"

# for protocol diagrams
[preprocessor.mermaid]
command = "mdbook-mermaid"
