[package]
name = "book"
version = "0.1.0"
edition = "2021"

[dependencies]
make = "0.0.0"
mdbook = "0.4.27"
mdbook-admonish = "1.8.0"
mdbook-katex = "0.3.8"
mdbook-mermaid = "0.12.6"
mdbook-toc = "0.11.2"
cargo-spec = "0.4.4"