# Tracking issue: https://github.com/o1-labs/mina-rust/issues/1984
name: No-Std Compatibility Check

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: no-std-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  no-std-check:
    name: "no_std: ${{ matrix.crate.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          # Crates with no-std feature
          - { name: "mina-hasher", path: "hasher" } # https://github.com/o1-labs/mina-rust/issues/1994
          - { name: "mina-poseidon", path: "poseidon" } # https://github.com/o1-labs/mina-rust/issues/1996
          - { name: "mina-signer", path: "signer" } # https://github.com/o1-labs/mina-rust/issues/1995
          - { name: "groupmap", path: "groupmap" } # https://github.com/o1-labs/mina-rust/issues/1985
          - { name: "o1-utils", path: "utils" } # https://github.com/o1-labs/mina-rust/issues/1988
          - { name: "poly-commitment", path: "poly-commitment" } # https://github.com/o1-labs/mina-rust/issues/1990
          # TODO: Add no-std feature to these crates
          # - { name: "wasm-types", path: "crates/wasm-types" }
          # - { name: "turshi", path: "turshi" } # https://github.com/o1-labs/mina-rust/issues/1986
          # - { name: "mina-curves", path: "curves" } # https://github.com/o1-labs/mina-rust/issues/1987
          # - { name: "internal-tracing", path: "internal-tracing" } # https://github.com/o1-labs/mina-rust/issues/1989
          # - { name: "kimchi", path: "kimchi" } # https://github.com/o1-labs/mina-rust/issues/1991
          # - { name: "kimchi-msm", path: "msm" } # https://github.com/o1-labs/mina-rust/issues/1992
          # - { name: "mvpoly", path: "mvpoly" } # https://github.com/o1-labs/mina-rust/issues/1993
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use shared Rust toolchain setting up steps
        uses: ./.github/actions/toolchain-shared
        with:
          rust_toolchain_version: stable

      - name: Check ${{ matrix.crate.name }} (no_std)
        run: |
          cd ${{ matrix.crate.path }}
          cargo check --features no-std --no-default-features
