[package]
name = "plonk_15_wires_plookup_protocol_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
commitment_dlog = { path = "../commitment" }
plonk_15_wires_circuits = { path = "../../circuits/plonk-15-wires" }
oracle = { path = "../../oracle" }
ocaml = { version = "0.18.1", optional = true }
rand_core = { version = "0.5" }
colored = "2.0.0"
rand = "0.8.0"
sprs = "0.9.2"
rayon = "1.5.0"
array-init = "1.0.0"

[features]

ocaml_types = [ "ocaml" ]
